# Generated by Django 4.0.2 on 2022-02-09 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='team', max_length=42)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accConnect.project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=75)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accConnect.team')),
            ],
        ),
    ]
